name: flutter_application
description: "A new Flutter project for a budgeting app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.2.0
  localstorage: ^6.0.0
  fl_chart: ^1.1.1
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
